HEARTBEAT_TOPIC = "/swarm/heartbeat"
DRONE_STATE_TOPIC = "/swarm/drone_state"
CLAIMS_TOPIC = "/swarm/claims"
CONSENSUS_RESULT_TOPIC = "/swarm/consensus_result"
CERTAINTY_UPDATE_TOPIC = "/swarm/certainty_update"
SURVIVOR_FOUND_TOPIC = "/swarm/survivor_found"
RUNTIME_CONTROL_TOPIC = "/swarm/runtime_control"
