from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol


class WebotsField(Protocol):
    def getSFVec3f(self) -> Sequence[float]: ...
    def setSFVec3f(self, value: Sequence[float]) -> None: ...

class WebotsNode(Protocol):
    def getPosition(self) -> Sequence[float]: ...
    def getField(self, field_name: str) -> WebotsField: ...

class WebotsRobot(Protocol):
    def getBasicTimeStep(self) -> float: ...
    def step(self, duration: int) -> int: ...

class WebotsSupervisor(WebotsRobot, Protocol):
    def getFromDef(self, def_name: str) -> WebotsNode | None: ...

class WebotsControllerModule(Protocol):
    def Robot(self) -> WebotsRobot: ...
    def Supervisor(self) -> WebotsSupervisor: ...
